version: "3"

services:

  library:
    build:
      context: .
    container_name: library
    image: library:latest
    ports:
      - 8888:8080
    depends_on:
      - mysql
    networks:
      - library-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/my_project
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_FLYWAY_URL=jdbc:mysql://mysql:3306
      - SPRING_FLYWAY_USER=root
      - SPRING_FLYWAY_PASSWORD=root

  mysql:
    image: mysql:8.0.31
    container_name: mysql-library
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - library-network
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

networks:
  library-network:

volumes:
  database:

